"""Plot UVM fusion performance as a two-panel scaling figure."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_INPUT = SCRIPT_DIR / "um_scaling_law.csv"
DEFAULT_OUTPUT_STEM = SCRIPT_DIR / "um_scaling_law"

PANEL_METHODS = {
    "Aggregation and weighting": [
        "concat",
        "mean fusion",
        "static global weight",
        "gated",
        "Ours",
    ],
    "Attention-based fusion": [
        "self attention",
        "cross attention",
        "Ours",
    ],
}

METHOD_STYLES = {
    "concat": {
        "label": "Concat",
        "color": "#4C78A8",
        "marker": "o",
        "linestyle": "-",
    },
    "mean fusion": {
        "label": "Mean",
        "color": "#59A14F",
        "marker": "s",
        "linestyle": "-",
    },
    "static global weight": {
        "label": "Static weight",
        "color": "#9C755F",
        "marker": "D",
        "linestyle": "--",
    },
    "gated": {
        "label": "Gated",
        "color": "#F28E2B",
        "marker": "^",
        "linestyle": "-.",
    },
    "self attention": {
        "label": "Self-attention",
        "color": "#B07AA1",
        "marker": "P",
        "linestyle": "--",
    },
    "cross attention": {
        "label": "Cross-attention",
        "color": "#2A9D8F",
        "marker": "X",
        "linestyle": "-",
    },
    "Ours": {
        "label": "Ours",
        "color": "#C43C39",
        "marker": "o",
        "linestyle": "-",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create the two-panel UVM foundation-model scaling figure."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument(
        "--output-stem",
        type=Path,
        default=DEFAULT_OUTPUT_STEM,
        help="Output path without extension; .svg and .pdf are added automatically.",
    )
    parser.add_argument(
        "--preview-png",
        type=Path,
        default=None,
        help="Optional PNG path for visual inspection; not generated by default.",
    )
    return parser.parse_args()


def load_data(path: Path) -> pd.DataFrame:
    data = pd.read_csv(path)
    required = {"model_num", "method", "auc", "std"}
    missing = required - set(data.columns)
    if missing:
        raise ValueError(f"Missing required columns in {path}: {sorted(missing)}")

    data = data.copy()
    data["model_num"] = pd.to_numeric(data["model_num"], errors="raise").astype(int)
    data["auc"] = pd.to_numeric(data["auc"], errors="raise")
    data["std"] = pd.to_numeric(data["std"], errors="raise")

    expected_methods = set(METHOD_STYLES)
    observed_methods = set(data["method"])
    missing_methods = expected_methods - observed_methods
    unexpected_methods = observed_methods - expected_methods
    if missing_methods or unexpected_methods:
        raise ValueError(
            "Method mismatch: "
            f"missing={sorted(missing_methods)}, unexpected={sorted(unexpected_methods)}"
        )
    if data.duplicated(["model_num", "method"]).any():
        duplicates = data.loc[data.duplicated(["model_num", "method"], keep=False)]
        raise ValueError(f"Duplicate n/method rows found:\n{duplicates}")
    return data.sort_values(["model_num", "method"])


def configure_matplotlib() -> None:
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 8.5,
            "axes.labelsize": 9,
            "axes.titlesize": 9.5,
            "axes.linewidth": 0.8,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 7.4,
            "legend.frameon": False,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def plot_method(ax: plt.Axes, data: pd.DataFrame, method: str) -> None:
    subset = data.loc[data["method"] == method].sort_values("model_num")
    style = METHOD_STYLES[method]
    is_ours = method == "Ours"
    ax.plot(
        subset["model_num"],
        subset["auc"],
        label=style["label"],
        color=style["color"],
        linestyle=style["linestyle"],
        linewidth=2.3 if is_ours else 1.35,
        marker=style["marker"],
        markersize=5.2 if is_ours else 4.2,
        markerfacecolor=style["color"],
        markeredgecolor="white" if is_ours else style["color"],
        markeredgewidth=0.8 if is_ours else 0.4,
        zorder=5 if is_ours else 3,
    )


def create_figure(data: pd.DataFrame) -> plt.Figure:
    configure_matplotlib()
    figure, axes = plt.subplots(
        1,
        2,
        figsize=(7.3, 3.45),
        sharex=True,
        sharey=True,
    )

    x_values = sorted(data["model_num"].unique())
    panel_labels = ["(a)", "(b)"]
    for ax, (panel_title, methods), panel_label in zip(
        axes, PANEL_METHODS.items(), panel_labels
    ):
        for method in methods:
            plot_method(ax, data, method)

        ax.set_title(f"{panel_label} {panel_title}", loc="left", pad=7, fontweight="semibold")
        ax.set_xlim(min(x_values) - 0.25, max(x_values) + 0.25)
        ax.set_xticks(x_values)
        ax.set_ylim(0.64, 0.91)
        ax.set_yticks([0.65, 0.70, 0.75, 0.80, 0.85, 0.90])
        ax.grid(axis="y", color="#D0D0D0", linewidth=0.65, linestyle="--", alpha=0.55)
        ax.tick_params(axis="both", direction="out", length=3, width=0.7)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.18),
            ncol=3,
            columnspacing=1.2,
            handlelength=2.2,
            handletextpad=0.45,
        )

    axes[0].set_ylabel("Mean AUC")
    figure.suptitle(
        "Fusion performance versus the number of integrated foundation models",
        x=0.5,
        y=0.975,
        fontsize=11.2,
        fontweight="semibold",
    )
    figure.supxlabel("Number of integrated foundation models ($n$)", y=0.035, fontsize=9)
    figure.subplots_adjust(left=0.085, right=0.995, bottom=0.285, top=0.82, wspace=0.10)
    return figure


def main() -> None:
    args = parse_args()
    data = load_data(args.input.resolve())
    output_stem = args.output_stem.resolve()
    output_stem.parent.mkdir(parents=True, exist_ok=True)

    figure = create_figure(data)
    svg_path = output_stem.with_suffix(".svg")
    pdf_path = output_stem.with_suffix(".pdf")
    figure.savefig(svg_path, format="svg", bbox_inches="tight", pad_inches=0.025)
    figure.savefig(pdf_path, format="pdf", bbox_inches="tight", pad_inches=0.025)
    if args.preview_png is not None:
        preview_path = args.preview_png.resolve()
        preview_path.parent.mkdir(parents=True, exist_ok=True)
        figure.savefig(preview_path, format="png", dpi=220, bbox_inches="tight", pad_inches=0.025)
        print(f"Saved preview: {preview_path}")
    plt.close(figure)

    print(f"Saved SVG: {svg_path}")
    print(f"Saved PDF: {pdf_path}")


if __name__ == "__main__":
    main()
